### ISSUE TITLE
Video playback blocked by Google

### ISSUE THREAD

**Issue by danieloneill** [BowDown097/QtTube#18]
Hi there! I can login and browse videos without any trouble, but playback results in the following:

![image](https://github.com/user-attachments/assets/82f92505-9c49-417a-b66f-a47dbf73c123)

When running in the terminal, I see plenty of cookie messages such as:

```
New cookie: __Secure-1PSID=g.a000sQFclGuoWt5mgx3D4g2gzQA2w2NPUYNJKqNaxs97YVKuz6oTsOtsmKS6ZkpSo-9Z1hg3QAACgYKASISARASFQHGX2Mi0jXOtjGK71wh5NAMovdedhoVAUF8yKq8ifxQ2QpchJxFPA_4oUSU0076
New cookie: __Secure-3PSID=g.a000sQgRlGuoWt5mgx3D4g2gzQA2w2NPUYNJKqNaxs97YVKuz6oTp9ekyBGOaf_AOutDB0a41AACgYKAbIQARASFQHGX2Mi6imWTDLKaeZl7bfMtOfxyRoVAUF8yKpeFizePLmX50RD8Wvrpbty0076
New cookie: HSID=AgQzaZ3tipbptZg9B
New cookie: SSID=A9CEyjqqVfikwGdmE

```

Git master 2ad0651c2050d07704ab231755fd83ad13675667
Qt 6.8.1
KDE Plasma 6.2.5

**Comment by danieloneill** [comment]
After logging in, I restarted the app and it worked right away, so I'll just close this issue after all. 🙂

**Comment by BowDown097** [comment]
Ran into this issue before, but forgot it existed. Thanks for the reminder. It's been fixed by the commit above.

**Comment by theogbob** [comment]
This issue happened to me recently too, I tried logging in and out but it still shows this, I tried updating to latest and falling back a few versions but it still doesnt work too

![Image](https://github.com/user-attachments/assets/97873297-1a61-4433-95d3-12d5960a1a87)

**Comment by theogbob** [comment]
It randomly fixed itself after a while when i reopened the app on latest ver, not sure why but it works now. Mabye keep an eye on it but idk lol.

**Comment by BowDown097** [comment]
Weird. Haven't had it happen to me since the commit that should have fixed it, and idk why it would happen still, but ya def still keeping an eye on it. Would be cool if Google provided error details for like anything at all.
